[package]
name = "wgpu-learn"
version = "0.1.0"
authors = ["liaodonghuo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[dependencies]
cgmath = "0.17"
env_logger = "0.7"
glsl-to-spirv = "0.1"
log = "0.4"
png = "0.15"
zerocopy = "0.2"
futures = "0.3"
lazy_static = "1.4.0"
wgpu = "0.5.0"
winit = { version = "0.22.1", features = ["web-sys"] }
rand = { version = "0.7.2", features = ["wasm-bindgen"] }
async-std = "1.5.0"




