[package]
name = "wgpu-learn"
version = "0.1.0"
authors = ["liaodonghuo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[dependencies]
arrayvec = "0.5"
smallvec = "1"
raw-window-handle = "0.3"
winit = "=0.20.0-alpha6"
cgmath = "0.17"
env_logger = "0.7"
glsl-to-spirv = "0.1"
log = "0.4"
png = "0.15"
rand = "0.7.2"
zerocopy = "0.2"
futures = "0.3"

[dev-dependencies]



[dependencies.wgpu]
package = "wgpu"
version = "0.4.0"
git = "https://github.com/gfx-rs/wgpu-rs.git"
rev = "4a0da16fe6764c4e1dc918a31cbd7467d404df51"